[package]
name = "day_6"
version = "0.0.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
divan = "0.1.17"

[[bench]]
name = "speed"
harness = false
